### ISSUE TITLE
What is the licence of your work?

### ISSUE THREAD

**Issue by cspaier** [v0ltis/WordPath#2]
I am interested in using your work and want to know if/how I can do such.

The best would be to choose and include a LICENCE file I guess.

Depending on your tastes, MIT, GPL or WTFPL are worth considering ;)

**Comment by barnabehvrd** [comment]
Done ! 

I've chosen the MIT licence.

Please, note that the code just got a little clean-up + a few more options (like a way to disable the length limit from the API), take a look at the new [README](https://github.com/v0ltis/WordPath#readme) ;)
